// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Token struct {
	AccessToken string `json:"AccessToken"`
}

type UpdateMovie struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
}
