// Code generated by github.com/vektah/dataloaden, DO NOT EDIT.

package dataloader

import (
	"sync"
	"time"

	"movie-review/graph/model"
)

// ReviewLoaderConfig captures the config to create a new ReviewLoader
type ReviewLoaderConfig struct {
	// Fetch is a method that provides the data for the loader
	Fetch func(keys []string, limit int, offset int) ([][]*model.MovieReview, []error)

	// Wait is how long wait before sending a batch
	Wait time.Duration

	// MaxBatch will limit the maximum number of keys to send in one batch, 0 = not limit
	MaxBatch int
}

// NewReviewLoader creates a new ReviewLoader given a fetch, wait, and maxBatch
func NewReviewLoader(config ReviewLoaderConfig) *ReviewLoader {
	return &ReviewLoader{
		fetch:    config.Fetch,
		wait:     config.Wait,
		maxBatch: config.MaxBatch,
	}
}

// ReviewLoader batches and caches requests
type ReviewLoader struct {
	// this method provides the data for the loader
	fetch func(keys []string, limit int, offset int) ([][]*model.MovieReview, []error)

	// how long to done before sending a batch
	wait time.Duration

	// this will limit the maximum number of keys to send in one batch, 0 = no limit
	maxBatch int

	// INTERNAL

	// lazily created cache
	cache map[string][]*model.MovieReview

	// the current batch. keys will continue to be collected until timeout is hit,
	// then everything will be sent to the fetch method and out to the listeners
	batch *reviewLoaderBatch

	// mutex to prevent races
	mu sync.Mutex
}

type reviewLoaderBatch struct {
	keys    []string
	data    [][]*model.MovieReview
	error   []error
	closing bool
	done    chan struct{}
	
}

// Load a MovieReview by key, batching and caching will be applied automatically
func (l *ReviewLoader) Load(key string, limit int, offset int) ([]*model.MovieReview, error) {
	return l.LoadThunk(key,limit,offset)()
}

// LoadThunk returns a function that when called will block waiting for a MovieReview.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *ReviewLoader) LoadThunk(key string, limit int, offset int) func() ([]*model.MovieReview, error) {
	l.mu.Lock()
	if it, ok := l.cache[key]; ok {
		l.mu.Unlock()
		return func() ([]*model.MovieReview, error) {
			return it, nil
		}
	}
	if l.batch == nil {
		l.batch = &reviewLoaderBatch{done: make(chan struct{})}
	}
	batch := l.batch
	pos := batch.keyIndex(l, key, limit, offset)
	l.mu.Unlock()

	return func() ([]*model.MovieReview, error) {
		<-batch.done

		var data []*model.MovieReview
		if pos < len(batch.data) {
			data = batch.data[pos]
		}

		var err error
		// its convenient to be able to return a single error for everything
		if len(batch.error) == 1 {
			err = batch.error[0]
		} else if batch.error != nil {
			err = batch.error[pos]
		}

		if err == nil {
			l.mu.Lock()
			l.unsafeSet(key, data)
			l.mu.Unlock()
		}

		return data, err
	}
}

// LoadAll fetches many keys at once. It will be broken into appropriate sized
// sub batches depending on how the loader is configured
func (l *ReviewLoader) LoadAll(keys []string, limit int, offset int) ([][]*model.MovieReview, []error) {
	results := make([]func() ([]*model.MovieReview, error), len(keys))

	for i, key := range keys {
		results[i] = l.LoadThunk(key,limit,offset)
	}

	movieReviews := make([][]*model.MovieReview, len(keys))
	errors := make([]error, len(keys))
	for i, thunk := range results {
		movieReviews[i], errors[i] = thunk()
	}
	return movieReviews, errors
}

// LoadAllThunk returns a function that when called will block waiting for a MovieReviews.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *ReviewLoader) LoadAllThunk(keys []string, limit int, offset int) func() ([][]*model.MovieReview, []error) {
	results := make([]func() ([]*model.MovieReview, error), len(keys))
	for i, key := range keys {
		results[i] = l.LoadThunk(key,limit,offset)
	}
	return func() ([][]*model.MovieReview, []error) {
		movieReviews := make([][]*model.MovieReview, len(keys))
		errors := make([]error, len(keys))
		for i, thunk := range results {
			movieReviews[i], errors[i] = thunk()
		}
		return movieReviews, errors
	}
}

// Prime the cache with the provided key and value. If the key already exists, no change is made
// and false is returned.
// (To forcefully prime the cache, clear the key first with loader.clear(key).prime(key, value).)
func (l *ReviewLoader) Prime(key string, value []*model.MovieReview) bool {
	l.mu.Lock()
	var found bool
	if _, found = l.cache[key]; !found {
		// make a copy when writing to the cache, its easy to pass a pointer in from a loop var
		// and end up with the whole cache pointing to the same value.
		cpy := make([]*model.MovieReview, len(value))
		copy(cpy, value)
		l.unsafeSet(key, cpy)
	}
	l.mu.Unlock()
	return !found
}

// Clear the value at key from the cache, if it exists
func (l *ReviewLoader) Clear(key string) {
	l.mu.Lock()
	delete(l.cache, key)
	l.mu.Unlock()
}

func (l *ReviewLoader) unsafeSet(key string, value []*model.MovieReview) {
	if l.cache == nil {
		l.cache = map[string][]*model.MovieReview{}
	}
	l.cache[key] = value
}

// keyIndex will return the location of the key in the batch, if its not found
// it will add the key to the batch
func (b *reviewLoaderBatch) keyIndex(l *ReviewLoader, key string, limit int, offset int) int {
	for i, existingKey := range b.keys {
		if key == existingKey {
			return i
		}
	}

	pos := len(b.keys)
	b.keys = append(b.keys, key)
	if pos == 0 {
		go b.startTimer(l, limit, offset)
	}

	if l.maxBatch != 0 && pos >= l.maxBatch-1 {
		if !b.closing {
			b.closing = true
			l.batch = nil
			go b.end(l,limit,offset)
		}
	}

	return pos
}

func (b *reviewLoaderBatch) startTimer(l *ReviewLoader, limit int, offset int) {
	time.Sleep(l.wait)
	l.mu.Lock()

	// we must have hit a batch limit and are already finalizing this batch
	if b.closing {
		l.mu.Unlock()
		return
	}

	l.batch = nil
	l.mu.Unlock()

	b.end(l,limit,offset)
}

func (b *reviewLoaderBatch) end(l *ReviewLoader, limit int, offset int) {
	b.data, b.error = l.fetch(b.keys,limit,offset)
	close(b.done)
}
